version: 2.1

executors:
  node:
    docker:
      - image: node:16-slim

jobs:
  lint-markdown:
    executor: node
    steps:
      - checkout
      - run:
          name: Install markdownlint
          command: npm install -g markdownlint-cli
      - run:
          name: Check for Lint
          command: markdownlint .

workflows:
  version: 2

  build-and-test:
    jobs:
      - lint-markdown
